### ISSUE TITLE
From value overrides user input (can't set a default value)

### ISSUE THREAD

**Issue by ushapax** [workingconcept/range-slider-craft-plugin#1]
So it looks like Ion uses the from data attribute as a default value for the single slider. Works for new entries. However, when editing existing entries the range slider is always initialized to the from value instead of the input value. Maybe a bug with Ion? 

I got this to work with a check and reset of the input value in the helper js function.

**Comment by mattstein** [comment]
Thanks @ushapax! Would you mind submitting a PR for that? This repo's in a weird place as it's just a [partially completed port of a Craft 2 plugin](https://github.com/MaxLazar/mx-rangeslider-craftcms/issues/7) (that I made to quickly get another project to Craft 3). I should probably point this out somewhere...

**Comment by mattstein** [comment]
Merged [PR](https://github.com/workingconcept/range-slider-craft-plugin/pull/2), thank you kindly.
