### ISSUE TITLE
Failed to instantiate component or class "workingconcept\rangeslider\assetbundles\RangeSlider\RangeSliderAsset"

### ISSUE THREAD

**Issue by remcoov** [workingconcept/range-slider-craft-plugin#3]
Hi,

I recently updated an 'old' Craft CMS install to 3.7.23, which uses this plugin. But now - on entries which use this plugin - I'm getting the error:

`Failed to instantiate component or class "workingconcept\rangeslider\assetbundles\RangeSlider\RangeSliderAsset"`

Any way to fix this for us? Would like to hear,

Greetings

**Comment by mattstein** [comment]
@remcoov I’m guessing it’s this non-PSR-4-compliant namespace: https://github.com/workingconcept/range-slider-craft-plugin/blob/master/src/assetbundles/RangeSliderAsset.php#L11

I haven’t touched this fork in a while and don’t have time to maintain it—you’re welcome to fix up that namespace and keep using it though!
